---
title: "Worst Data Viz"
author: "Hailey Veirs"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)

library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

# And for another dataset we'll explore:
library(gapminder)
```


```{r}
space_data <- read_csv(here("data", "space_launches.csv")) 

```


```{r}
space_data_atlas <- space_data |> 
  filter(str_detect(type, pattern = "Atlas")) |> 
  group_by(type) |> 
  mutate(n_type = n()) |> 
  group_by(type, agency) |>
  summarize(n_type_agency = n(), 
            n_type = first(n_type)) |> 
  mutate(proportion_type_agency = n_type_agency / n_type)

col_graph <- ggplot(space_data_atlas, 
                    aes(x = type, y = proportion_type_agency)) + 
  geom_col(position = "fill", aes(fill = proportion_type_agency)) + 
  scale_fill_paletteer_c(palette = "grDevices::rainbow") + 
  theme(panel.grid.major.x = element_line(color = "gold"), 
        panel.grid.minor.y = element_blank(), 
        axis.title = element_text(color = "orange", size = 14), 
        axis.text.y = element_text(color = "blue", size = 5), 
        text = element_text(size = 14), 
        panel.background = element_rect(fill = "grey")) + 
  labs(title = "SPACE PROPORTIONS!!!", 
       x = "Type! :D", 
       y = "idek what this is (%)")

col_graph

```




